# Vectorization

# Why Vectorization?

- Vectorization means applying operations to whole arrays instead of looping element-by-element.
- In Python, loops are slower than NumPy array operations, because NumPy uses optimized native code.
- Vectorized code is shorter, easier to read, and much faster for large datasets.

In [33]:
import numpy as np

x = np.array([[1, 2, 3, 4, 5],
         [6,7,8,9,10],
         [11,12,13,14,15],
         [16,17,18,19,20],
         [21,22,23,24,25]])
w = np.arange(1, 6)

print(x)
print(w)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]


In [35]:
np.dot(x, w.T) + 1

array([ 56, 131, 206, 281, 356])

In [63]:
y

In [71]:
np.random.rand(1, 5).shape

(1, 5)